name: CI-pipeline

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkoutcode
        uses: actions/checkout@v3

      - name: login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUBUSER}}
          password: ${{secrets.DOCKERHUBPASS}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run : |
          pip install -r requirements.txt


      - name: Build Docker images
        run: |
          docker build -t sahilmahat/multicicd:${{ github.sha }}
          docker tag sahilmahat/multicicd:${{ github.sha }} 
          docker tag sahilmahat/multicicd:latest

      - name: Push Docker Image
        run: |
          docker push sahilmahat/multicicd:${{ github.sha }}
          docker push sahilmahat/multicicd:latest


  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Depoy on dev
        run: |
          echo "Deploy on dev env"

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy on Stage
        run: |
          echo "Deply on Staging"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy on Prod
        run: |
          echo "Deploy on Prod"
